/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as SectionSlugRouteImport } from './routes/section.$slug'
import { Route as TvIdRouteImport } from './routes/tv.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSlugRoute = SectionSlugRouteImport.update({
  id: '/section/$slug',
  path: '/section/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/section/$slug': typeof SectionSlugRoute
  '/tv/$id': typeof TvIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/section/$slug': typeof SectionSlugRoute
  '/tv/$id': typeof TvIdRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/section/$slug': typeof SectionSlugRoute
  '/tv/$id': typeof TvIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/api/chat'
    | '/chat/$threadId'
    | '/movie/$id'
    | '/section/$slug'
    | '/tv/$id'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/api/chat'
    | '/chat/$threadId'
    | '/movie/$id'
    | '/section/$slug'
    | '/tv/$id'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/api/chat'
    | '/chat/$threadId'
    | '/movie/$id'
    | '/section/$slug'
    | '/tv/$id'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  MovieIdRoute: typeof MovieIdRoute
  SectionSlugRoute: typeof SectionSlugRoute
  TvIdRoute: typeof TvIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$slug': {
      id: '/section/$slug'
      path: '/section/$slug'
      fullPath: '/section/$slug'
      preLoaderRoute: typeof SectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  MovieIdRoute: MovieIdRoute,
  SectionSlugRoute: SectionSlugRoute,
  TvIdRoute: TvIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
